services:
  database:
    image: mysql:lts
    container_name: flights-db-hw-3-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inflight_catering_service
